########## Oauth config #####################
BASE_URL =https://janparichaystag.meripehchaan.gov.in
AUTHORIZE_URL =https://janparichaystag.meripehchaan.gov.in/v1/oauth2/authorize
TOKEN_URL =https://janparichaystag.meripehchaan.gov.in/v1/salt/api/oauth2/token
USER_DETAILS_URL =https://janparichaystag.meripehchaan.gov.in/v1/salt/api/oauth2/userdetails
REFRESH_URL=https://janparichaystag.meripehchaan.gov.in/v1/salt/api/oauth2/token
REVOKE_URL =https://janparichaystag.meripehchaan.gov.in/v1/salt/api/oauth2/revoke

CLIENT_ID =oauthcliente4l1qijq8cmwsob27gpqf
CLIENT_SECRET =2DTALF-m8yxbCOABwfJckMkrfavbFdQg
REDIRECT_URI =http://oauthclient.staging.nic.in/callback
		
SCOPE =user_details
RESPONSE_TYPE =code
CODE_CHALLENGE_METHOD =S256
